service: express-serverless-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: api

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

package: 
  individually: true

plugins:
  - serverless-offline